### ISSUE TITLE
List not loading

### ISSUE THREAD

**Issue by hiimshana** [AzSiAz/LN-Reader#13]
Hi,
First of all, I want to thank you for creating an app like this, that's basically the dream of every ln reader...
Then, I apologize if this isn't the right section to send an issue, since this is my first time using GitHub.

Now: my problem is simple. If I try to open the app it says "Loading list" forever. I tried leaving it "load" for about 10 minutes and nothing changed.
I don't think it's a connection problem since I'm currently on a 7mb/s connection (not much but should load a list of novels without problems). I tried with mobile connection (3G) too.
Sadly, I don't know how to send screenshots from mobile version of the site :/
Thanks for attention and all the effort you put in it!

Spec:
Device: iPhone 5C
Memory: 16 GB
OS: iOS 10.3.3

**Comment by AzSiAz** [comment]
Hi, 
Thank :)

Don't worry It's the right place, if there is a problem

Concerning your problem, I forgot to update my https certificate last saturday which should be the cause of your problem, I just update it and on my side it's loading fine, try again and tell me if wether it's working or not

**Comment by KamenRiderConstell** [comment]
I have the same problem. I even left the app open overnight and it still won’t load. I have 5 bars constantly. I don’t know how to send a screenshot either, but if there is something I can do (other than use Baka-tsuki on chrome) please tell me! Or you can try doing your https thing again

**Comment by AzSiAz** [comment]
Sorry about this, same problem as last time but it should be working as of now
