### ISSUE TITLE
List Not Loading

### ISSUE THREAD

**Issue by Tomkrusader** [AzSiAz/LN-Reader#15]
Hi, similar to an issue that was previously closed months back, the list(actually the app in general) is not loading again for some reason. I tried waiting over an hour for the list to load but it's stuck with "Loading List" on a blank page. 
I really love this app, i would go as far as to say that this is the best free light novel app i have found on the IOS. I've been using this app quite actively so i would really appreciate it if the issue could be fixed so that i may continue using this platform.
Thank You.

**Comment by AzSiAz** [comment]
Hello, sorry about this again...
Should work now

**Comment by Tomkrusader** [comment]
Thank you so much!
